# Generated by Django 5.1.1 on 2024-09-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_aircraft_alter_country_id_alter_office_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='airport',
            name='country',
        ),
        migrations.RemoveField(
            model_name='route',
            name='departure_airport',
        ),
        migrations.RemoveField(
            model_name='route',
            name='arrival_airport',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='route',
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
