# Generated by Django 5.1.1 on 2024-10-04 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_code', models.CharField(choices=[('Q1', 'Пожалуйста, оцените самолет, на котором Вы летели с AMONIC Airlines'), ('Q2', 'Как бы Вы оценили наших борт проводников'), ('Q3', 'Как бы Вы оценили развлечения во время полета'), ('Q4', 'Пожалуйста, оцените цену на билет Вашего маршрута')], max_length=2, unique=True)),
                ('question_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.IntegerField(choices=[(1, 'Outstanding / Великолепно'), (2, 'Very Good / Очень хорошо'), (3, 'Good / Хорошо'), (4, 'Adequate / Нормально'), (5, 'Needs Improvement / Необходимо улучшить'), (6, 'Poor / Плохо'), (7, 'Don’t know / Не знаю'), (0, 'Не ответил')], default=0)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('ticket_type', models.CharField(blank=True, max_length=50, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.surveyquestion')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.schedule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
