# Generated by Django 5.1.1 on 2024-10-03 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight', '0001_initial'),
        ('user', '0006_remove_schedule_aircraft_remove_airport_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('passport_number', models.CharField(max_length=20)),
                ('booking_reference', models.CharField(max_length=100)),
                ('confirmed', models.BooleanField(default=False)),
                ('cabin_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.cabintype')),
                ('passport_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.country')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight.schedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
