# Generated by Django 5.1.1 on 2025-02-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="booking_reference",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
